/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package HotelBooking;
import java.awt.CardLayout;

import javax.swing.JPanel;
/**
 *
 * @author Wuan
 */
public class LoginPanel extends javax.swing.JPanel {
    private JPanel cardPanel;
    /**
     * Creates new form LoginPanel
     */
    
    public LoginPanel(JPanel cardPanel) {
        this.cardPanel = cardPanel;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NoTouch4 = new javax.swing.JPanel();
        Btn_DoSignIn = new javax.swing.JButton();
        Btn_Cancel = new javax.swing.JButton();
        Title_Signin = new javax.swing.JLabel();
        Title_UserName = new javax.swing.JLabel();
        Title_Pwd = new javax.swing.JLabel();
        ShowPwd = new javax.swing.JCheckBox();
        Pattern_PhoneNumber = new javax.swing.JTextField();
        Pattern_Pwd = new javax.swing.JPasswordField();
        NoTouch = new javax.swing.JPanel();
        Btn_Regis = new javax.swing.JButton();
        NoTouch2 = new javax.swing.JLabel();
        BeGuest = new javax.swing.JButton();
        NoTouch3 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(748, 467));

        NoTouch4.setBackground(new java.awt.Color(223, 234, 253));

        Btn_DoSignIn.setBackground(new java.awt.Color(204, 255, 255));
        Btn_DoSignIn.setText("Sign In");
        Btn_DoSignIn.addActionListener(this::Btn_DoSignInActionPerformed);

        Btn_Cancel.setBackground(new java.awt.Color(155, 176, 245));
        Btn_Cancel.setText("Cancel");

        javax.swing.GroupLayout NoTouch4Layout = new javax.swing.GroupLayout(NoTouch4);
        NoTouch4.setLayout(NoTouch4Layout);
        NoTouch4Layout.setHorizontalGroup(
            NoTouch4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NoTouch4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(Btn_DoSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Btn_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(394, Short.MAX_VALUE))
        );
        NoTouch4Layout.setVerticalGroup(
            NoTouch4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NoTouch4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(NoTouch4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Btn_Cancel, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(Btn_DoSignIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        Title_Signin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Title_Signin.setText("Sign In");

        Title_UserName.setText("User Name");

        Title_Pwd.setText("Password");

        ShowPwd.setText("Show Password");
        ShowPwd.addActionListener(this::ShowPwdActionPerformed);

        Pattern_PhoneNumber.setText("userPhoneNumber");
        Pattern_PhoneNumber.addActionListener(this::Pattern_PhoneNumberActionPerformed);

        Pattern_Pwd.setText("userPassword");

        NoTouch.setBackground(new java.awt.Color(205, 224, 243));

        Btn_Regis.setBackground(new java.awt.Color(121, 187, 248));
        Btn_Regis.setText("Register an Account");

        NoTouch2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        NoTouch2.setText("Don't have an account ?");

        BeGuest.setBackground(new java.awt.Color(121, 187, 248));
        BeGuest.setText("Continue as Guest User");
        BeGuest.addActionListener(this::BeGuestActionPerformed);

        NoTouch3.setText("OR");

        javax.swing.GroupLayout NoTouchLayout = new javax.swing.GroupLayout(NoTouch);
        NoTouch.setLayout(NoTouchLayout);
        NoTouchLayout.setHorizontalGroup(
            NoTouchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NoTouchLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NoTouch3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
            .addGroup(NoTouchLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(NoTouchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BeGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Regis, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoTouch2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        NoTouchLayout.setVerticalGroup(
            NoTouchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NoTouchLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(NoTouch2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Regis, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NoTouch3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BeGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Title_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Pattern_Pwd)
                                        .addComponent(Pattern_PhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Title_Pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ShowPwd))
                                .addGap(40, 40, 40)
                                .addComponent(NoTouch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Title_Signin, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(NoTouch4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(Title_Signin, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Title_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Pattern_PhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(Title_Pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pattern_Pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ShowPwd))
                    .addComponent(NoTouch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(NoTouch4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_DoSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DoSignInActionPerformed
        // TODO add your handling code here:
        /*
        Can kiem tra xem user co trong database ko
        Neu co thi mo cua so tim kiem cho user
        Neu khong thi hien thong bao loi
        JOptionPane.showMessageDialog(null, "Login Success");
        JOptionPane.showMessageDialog(null, "Login Error");
        */
    }//GEN-LAST:event_Btn_DoSignInActionPerformed

    private void ShowPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPwdActionPerformed
        // TODO add your handling code here:
        if (ShowPwd.isSelected()) {
            Pattern_Pwd.setEchoChar((char)0); // Hiển thị mật khẩu
        } else {
            Pattern_Pwd.setEchoChar('\u25CF'); // Ẩn mật khẩu
        }
    }//GEN-LAST:event_ShowPwdActionPerformed

    private void Pattern_PhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pattern_PhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pattern_PhoneNumberActionPerformed

    private void BeGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeGuestActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) cardPanel.getLayout();
        cl.show(cardPanel, "Main");
    }//GEN-LAST:event_BeGuestActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Regis;
    private javax.swing.JButton BeGuest;
    private javax.swing.JButton Btn_DoSignIn;
    private javax.swing.JButton Btn_Cancel;
    private javax.swing.JCheckBox ShowPwd;
    private javax.swing.JLabel Title_Signin;
    private javax.swing.JLabel Title_UserName;
    private javax.swing.JLabel Title_Pwd;
    private javax.swing.JLabel NoTouch2;
    private javax.swing.JLabel NoTouch3;
    private javax.swing.JPanel NoTouch;
    private javax.swing.JPanel NoTouch4;
    private javax.swing.JPasswordField Pattern_Pwd;
    private javax.swing.JTextField Pattern_PhoneNumber;
    // End of variables declaration//GEN-END:variables
}
