/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package HotelBooking;
import Entity.DatabaseControl;
import Entity.User;
/**
 *
 * @author Wuan
 */
public class RegisterPanel extends javax.swing.JPanel {
    static int num = 0;
    /**
     * Creates new form RegisterPanel
     */
    public RegisterPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        

        createAccount = new javax.swing.JButton();
        backToLogin = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        Title_FullName = new javax.swing.JLabel();
        Pattern_Fullname = new javax.swing.JTextField();
        Title_PhoneNumber = new javax.swing.JLabel();
        Pattern_PhoneNumber = new javax.swing.JTextField();
        Title_Email = new javax.swing.JLabel();
        Pattern_Email = new javax.swing.JTextField();
        Title_Pwd = new javax.swing.JLabel();
        Pattern_Pwd = new javax.swing.JPasswordField();

        createAccount.setBackground(new java.awt.Color(0, 255, 51));
        createAccount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        createAccount.setForeground(new java.awt.Color(255, 255, 255));
        createAccount.setText("CREATE ACCOUNT");
        createAccount.addActionListener(this::createAccountActionPerformed);

        backToLogin.setBackground(new java.awt.Color(204, 204, 204));
        backToLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backToLogin.setForeground(new java.awt.Color(255, 255, 255));
        backToLogin.setText("BACK TO LOGIN");

        Title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("CREATE ACCOUNT");

        Title_FullName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Title_FullName.setText("Full Name");

        Pattern_Fullname.setText("Nguyen Van A");

        Title_PhoneNumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Title_PhoneNumber.setText("Phone Number");

        Pattern_PhoneNumber.setText("0123456789");
        Pattern_PhoneNumber.addActionListener(this::Pattern_PhoneNumberActionPerformed);

        Title_Email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Title_Email.setText("Email");

        Pattern_Email.setText("xxxx@gmail.com");

        Title_Pwd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Title_Pwd.setText("Password");

        Pattern_Pwd.setText("Pattern_Pwd");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Pattern_Fullname)
                            .addComponent(Pattern_PhoneNumber)
                            .addComponent(Pattern_Email)
                            .addComponent(Pattern_Pwd)
                            .addComponent(createAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(backToLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Title_Pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Title_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Title_PhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Title_FullName, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Title_FullName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pattern_Fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Title_PhoneNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Pattern_PhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Title_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pattern_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Title_Pwd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Pattern_Pwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(createAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backToLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountActionPerformed
        // TODO add your handling code here:
        String numConvert = Integer.toString(num);
        num += 1;
        User user = new User(numConvert, Pattern_Fullname.getText(), Pattern_Email.getText(),
            new String(Pattern_Pwd.getPassword()), Pattern_PhoneNumber.getText());
        DatabaseControl dbControl = new DatabaseControl();
        dbControl.insertTable(user.register());
        new LoginPanel();
    }//GEN-LAST:event_createAccountActionPerformed

    private void Pattern_PhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pattern_PhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pattern_PhoneNumberActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createAccount;
    private javax.swing.JButton backToLogin;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Title_FullName;
    private javax.swing.JLabel Title_PhoneNumber;
    private javax.swing.JLabel Title_Email;
    private javax.swing.JLabel Title_Pwd;
    private javax.swing.JPasswordField Pattern_Pwd;
    private javax.swing.JTextField Pattern_Fullname;
    private javax.swing.JTextField Pattern_PhoneNumber;
    private javax.swing.JTextField Pattern_Email;
    // End of variables declaration//GEN-END:variables
}
